name = "premiership-predictions"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[env.production]
vars = { API_KEY = "6885d2b0afmshf350fdf2ca5a6cbp15cfafjsn3681a13d3b3d" }

[env.preview]
vars = { API_KEY = "6885d2b0afmshf350fdf2ca5a6cbp15cfafjsn3681a13d3b3d" }
